"use strict";
let firstName = 'Joao';
alert(`Hello ${firstName}`);
let number1 = 0;
let number2 = 0;
let total = 0;
number1 = Number(prompt('Please insert the first number'));
number2 = Number(prompt('Please insert the second number'));
total = number1 + number2;
alert(`The sum between ${number1} and ${number2} = ${total}`);
